spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://user-service.mysql.database.azure.com/boardDB?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: nanum
    password: spharos1234!
