token:
  expiration_time: 864000000
  secret: "{cipher}AQAEWFTJRdbsNlAinvOYB++G8ZWC0+mF1aNQ1hj4Nu3KQynJzz11VWK0Yx7FvJT4464BVYxpUHL2UDKgFYSA+E7rYWwr+4qhdOY7iQ6DwcIxA9bzbabpTVvfTFVKD8nE4a8WKz0RP5J9GHb+4E1j3qmvL4lmyC2So9IiqlatVHeT2v1EyDTBt25lqfjo1Xvj+m4AyqZTEvjl5QOBQbuFSfBhwqGf6Cz1Cj7IyB7Iht/+ta94HYPLKMA5CUqTR75U7aeQxp3K56PNB+9VqY7M50WF7fO/88Wdi+JYGjMVOhZbrVkId+pPwcLbXHqAP+gF2QiaePZf28TLWbh5GvuchbHKg1eJ74iKSWap6hIkVYRqh391Z7xHKrlKQHKYM9lmSWzOY/nWPNchO2Jan+/OvNLt"

# spring:
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/house?serverTimezone=Asia/Seoul
#     username: root
#     password: 1234

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://user-service.mysql.database.azure.com/houseDB?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: nanum
    password: spharos1234!
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://house-service-db.cagqpalbhk0j.ap-northeast-2.rds.amazonaws.com:3306/houseDB?serverTimezone=Asia/Seoul
#     username: nanum
#     password: spharos1234!
  

cloud:
  aws:
    credentials:
      accessKey: AKIA6JUYLGWCXCTO5OO4
      secretKey: 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
    s3:
      bucket: nanum-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
# spring:
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/house?serverTimezone=Asia/Seoul
#     username: root
#     password: 1234

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://user-service.mysql.database.azure.com/houseDB?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: nanum
    password: spharos1234!
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://house-service-db.cagqpalbhk0j.ap-northeast-2.rds.amazonaws.com:3306/houseDB?serverTimezone=Asia/Seoul
#     username: nanum
#     password: spharos1234!
  

cloud:
  aws:
    credentials:
      accessKey: AKIA6JUYLGWCXCTO5OO4
      secretKey: 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
    s3:
      bucket: nanum-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
