spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul"
    username: root
    password: 1234

# gateway:
#   ip: 172.18.0.5

token:
  expiration_time: 864000000
  secret: "{cipher}AQAEWFTJRdbsNlAinvOYB++G8ZWC0+mF1aNQ1hj4Nu3KQynJzz11VWK0Yx7FvJT4464BVYxpUHL2UDKgFYSA+E7rYWwr+4qhdOY7iQ6DwcIxA9bzbabpTVvfTFVKD8nE4a8WKz0RP5J9GHb+4E1j3qmvL4lmyC2So9IiqlatVHeT2v1EyDTBt25lqfjo1Xvj+m4AyqZTEvjl5QOBQbuFSfBhwqGf6Cz1Cj7IyB7Iht/+ta94HYPLKMA5CUqTR75U7aeQxp3K56PNB+9VqY7M50WF7fO/88Wdi+JYGjMVOhZbrVkId+pPwcLbXHqAP+gF2QiaePZf28TLWbh5GvuchbHKg1eJ74iKSWap6hIkVYRqh391Z7xHKrlKQHKYM9lmSWzOY/nWPNchO2Jan+/OvNLt"

# sms:
#   senderPhone: 01046447221
#   serviceId: ncp:sms:kr:293418085250:nanum-sms
#   accessKey: I7wL0G67VkWWSsQo1YJV
#   secretKey: DFziahn2T1xgHLFyjGR78gmGc57QuwdTc5Wk1cAX
